apiVersion: v2
appVersion: 0.0.1
description: LLM inference in C/C++
icon: https://user-images.githubusercontent.com/1991296/230134379-7181e485-c521-4d23-a0d6-f7b3b61ba524.png
kubeVersion: '>= 1.25.0'
maintainers:
- email: carlos@kalavai.net
  name: Carlos Fernandez Musoles
  url: https://kalavai.net
name: llama.cpp
sources:
- https://github.com/ggml-org/llama.cpp
version: 0.0.1
