backend: cpu
cpus: 2
hfToken: null
lagoApiKey: null
lagoEventCode: null
lagoEventInterval: null
lagoExternalSubscriptionId: null
lagoUrl: null
litellmAccessGroup: null
litellmBaseUrl: http://litellm.default.svc.cluster.local:4000
litellmKalavaiExtras: '{}'
litellmKey: null
memory: 4
modelFilename: null
modelNameOverride: null
nodeport: null
parallel: 1
repoId: null
serverExtra: null
system:
  jobId: null
  priorityClassName: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
workers: 1
workingMemory: 5
