apiVersion: v2
appVersion: 0.0.1
description: Serverless is a template that allows you to deploy docker containers on
  your cluster.
icon: ''
kubeVersion: '>= 1.25.0'
maintainers:
- email: carlos@kalavai.net
  name: Carlos Fernandez Musoles
  url: https://kalavai.net
name: serverless
sources:
- ''
version: 0.0.1
