apiVersion: v1
stringData:
  hf_token: {{ .Values.hfToken }}
  litellm_key: {{ .Values.litellmKey }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    kalavai.job.name: {{ .Release.Name }}
type: Opaque
immutable: true