kalavaiApiImageTag: 0.8.10
kalavaiApiVersion: 0.1.13
system:
  jobPriority: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
watcherAdminKey: admin_key
watcherImageTag: 2026.1.2
watcherReadonlyKey: readonly_key
watcherVersion: 0.4.21
watcherWriteKey: write_key
