apiVersion: v1
stringData:
  watcherAdminKey: {{ .Values.watcherAdminKey }}
  watcherWriteKey: {{ .Values.watcherWriteKey }}
  watcherReadonlyKey: {{ .Values.watcherReadonlyKey }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
type: Opaque
immutable: true
