# expose kalavai api service
apiVersion: v1
kind: Service
metadata:
  name: pool-service
  labels:
    # must have this!
    kalavai.job.name: {{ .Values.system.jobId}}
spec:
  type: NodePort
  selector:
    app: {{ .Release.name}}-api-app
  ports:
    - name: api
      port: 8000
      targetPort: 8000
      protocol: TCP