apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    # must have this!
    kalavai.job.name: {{ .Values.system.jobId }}
spec:
  type: NodePort
  selector:
    role: leader
    kalavai.job.name: {{ .Values.system.jobId }}
  ports:
  - name: port-{{ .Values.port }}
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
  # {{- range .Values.ports }}
  # - name: port-{{ . }}
  #   port: {{ . }}
  #   targetPort: {{ . }}
  #   protocol: TCP
  # {{- end }}